### ISSUE TITLE
Wanneer je scherm wisselt, komt er een flikker moment tijdens laden nieuwe scherm.

### ISSUE THREAD

**Issue by berend109** [keesveldkamp18/the-ninja-warrior#6]
Mogelijke oplossing is om er een sleep op te zetten.

**Comment by ghost** [comment]
Sleep werkt niet en het is maar een minuscuul probleem.

**Comment by ghost** [comment]
Opgelost door meerdere canvassen te gebruiken in plaats van vensters.
